server:
  port: 8099

spring:
  jpa:
    database: H2
    show-sql: "true"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
  liquibase:
    change-log: classpath:db/changesets/master.xml
    check-change-log-location: true
    enabled: true
  datasource:
    driver-class-name: "org.h2.Driver"
    url: ${DATASOURCE_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${POSTGRES_PASSWORD:sa}