swagger: '2.0'
info:
  version: 1.0.0
  title: API сервиса управления счетами клиентов
  contact:
    name: Анасов Сергей
    email: sanasov@yandex.ru
basePath: /v1
tags:
- name: Account
  description: REST API для операций со счетами
paths:
  /accounts/transfer:
    post:
      tags:
      - Account
      summary: Перевод с одного счета на другой
      operationId: "transfer"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: transferRequest
          schema:
            $ref: '#/definitions/TransferRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OperationResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/OperationResponse'
        '404':
          description: Not Found
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal exception
          schema:
            $ref: '#/definitions/OperationResponse'
  /accounts/{accountNumber}/withdraw:
    post:
      tags:
      - Account
      summary: Метод для списания средств со счета
      operationId: "withdraw"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: accountNumber
        in: path
        description: номер счета списания
        required: true
        type: string
        pattern: '^\d{20}$'
      - in: body
        name: operationData
        schema:
          $ref: '#/definitions/OperationData'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OperationResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/OperationResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal exception
          schema:
            $ref: '#/definitions/OperationResponse'
  /accounts/{accountNumber}/deposit:
    post:
      tags:
        - Account
      summary: Метод для списания средств со счета
      operationId: "deposit"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: accountNumber
          in: path
          description: номер счета зачисления
          required: true
          type: string
          pattern: '^\d{20}$'
        - in: body
          name: operationData
          schema:
            $ref: '#/definitions/OperationData'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OperationResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/OperationResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal exception
          schema:
            $ref: '#/definitions/OperationResponse'
definitions:
  TransferRequest:
    type: object
    required:
    - accountNumberFrom
    - accountNumberTo
    - sumRub
    properties:
      accountNumberFrom:
        type: string
        description: номер счета списания
        pattern: '^\d{20}$'
      accountNumberTo:
        type: string
        pattern: '^\d{20}$'
        description: номер счета зачисления
      operationData:
        $ref: '#/definitions/OperationData'
        description: данные операции перевода (сумма, валюта и т.д)
    title: TransferRequest
  OperationData:
    type: object
    properties:
      sumRub:
        type: number
        description: сумма списания или зачисления
        minimum: 1
    title: OperationParam
  OperationResponse:
    type: object
    required:
    - messageResult
    properties:
      messageResult:
        type: string
        description: результат операции
    title: OperationResponse