swagger: '2.0'
info:
  description: Rest api для СП
  version: 1.0.0-SNAPSHOT
  title: API для структурных продуктов
  contact:
    name: Анасов Сергей
    email: sanasov@yandex.ru
basePath: /v1
tags:
- name: Account
  description: REST API для операций со счетами
paths:
  /accounts/transfer:
    put:
      tags:
      - Account
      summary: Получение полной информации об оферте
      operationId: "transfer"
      produces:
      - application/json
      parameters:
      - name: offerId
        in: path
        description: id оферты
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/OfferFullResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal exception
          schema:
            $ref: '#/definitions/ErrorResponse'
  /accounts/withdraw:
    put:
      tags:
      - Account
      summary: Метод для проверки возможности покупки клиентом оферты и получение ген.согов и счетов
      operationId: "withdraw"
      produces:
      - application/json
      parameters:
      - name: clientId
        in: path
        description: id учётной записи Клиента
        required: true
        type: string
        format: uuid
      - name: offerId
        in: path
        description: id оферты
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ClientOfferCheckResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal exception
          schema:
            $ref: '#/definitions/ErrorResponse'
  /accounts/deposit:
    put:
      tags:
      - Front System
      summary: Метод для отправки поручения на покупку СП
      operationId: "deposit"
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: buySPRequest
        description: Данные для поручения
        required: true
        schema:
          $ref: '#/definitions/BuySPRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/BuySPResponse'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal exception
          schema:
            $ref: '#/definitions/ErrorResponse'
securityDefinitions:
  oauth2:
    type: oauth2
    tokenUrl: >-
      https://auth.tusvc.bcs.ru/auth/realms/perseus/protocol/openid-connect/token
    flow: password
definitions:
  VerifyRequest:
    type: object
    required:
    - contractId
    properties:
      otp:
        type: number
        description: OTP код
  VerifyResponse:
    type: object
    properties:
      status:
        type: string
        description: "MATCH / DISMATCH"
  BuySPRequest:
    type: object
    required:
    - offerId
    - agreement
    - clientId
    - subaccount
    - summ
    properties:
      offerId:
        type: string
        description: id офферты
        format: uuid
      clientId:
        type: string
        description: id учётной записи Клиента
        format: uuid
      agreement:
        type: string
        description: Номер выбранного клиентом ГенСога
      subaccount:
        type: string
        description: Выбранный клиентом субсчёт
      summ:
        type: number
        description: Сумма поручения
    title: BuySPRequest
  OfferListResponse:
    type: object
    properties:
      marketingProductTypes:
        type: array
        items:
          $ref: '#/definitions/OfferProductType'
    title: OfferListResponse
  OfferProductType:
    type: object
    properties:
      name:
        type: string
      productMarketingNames:
        type: array
        items:
          $ref: '#/definitions/OfferProduct'
      riskProfile:
        $ref: '#/definitions/RiskProfile'
    title: OfferProductType
  RiskProfile:
    type: object
    properties:
      code:
        type: string
        format: uuid
      value:
        type: string
    title: RiskProfile
  OfferProduct:
    type: object
    properties:
      name:
        type: string
      offers:
        type: array
        items:
          $ref: '#/definitions/OfferDto'
    title: OfferProduct
  OfferDto:
    type: object
    properties:
      id:
        type: string
        format: uuid
      currency:
        type: string
      iis:
        type: boolean
      minFrontSystem:
        type: number
      periodYear:
        type: string
      periodMonth:
        type: string
      dateEnd:
        type: string
      profitability:
        type: string
      underlyingAssets:
        type: "array"
        items:
          $ref: '#/definitions/UnderlyingAsset'
    title: Offers
  UnderlyingAsset:
    type: object
    properties:
      id:
        type: string
        format: uuid
      currency:
        type: string
      decoding:
        type: string
      description:
        type: string
      name:
        type: string
      ticker:
        type: string
      isin:
        type: string
      exchange:
        type: string
      typesset:
        type: string
      emblem:
        type: string
    title: UnderlyingAsset
  OfferFullResponse:
    type: object
    properties:
      id:
        type: string
        format: uuid
      marketingProductTypes:
        type: string
      productMarketingNames:
        type: string
      currency:
        type: string
      currencySettlement:
        type: string
      iis:
        type: boolean
      minFrontSystem:
        type: number
      periodYear:
        type: string
      periodMonth:
        type: string
      dateEnd:
        type: string
      profitability:
        type: string
      barrierCoupon:
        type: string
      barrierReview:
        type: string
      investmentIdea:
        type: boolean
      correctionFactor:
        type: string
      marketingInfo:
        $ref: '#/definitions/MarketingInfoParameter'
      couponDates:
        $ref: '#/definitions/CouponDates'
      underlyingAssets:
        type: array
        items:
          $ref: '#/definitions/UnderlyingAsset'
      riskProfile:
        $ref: '#/definitions/RiskProfile'
    title: OfferFullResponse
  CouponDates:
    type: object
    properties:
      value:
        type: array
        items:
          $ref: '#/definitions/CouponDatesParameter'
    title: CouponDates
  CouponDatesParameter:
    type: object
    properties:
      number:
        type: string
      date:
        type: string
    title: CouponDatesParameter
  MarketingInfoParameter:
    type: object
    properties:
      descriptionProduct:
        type: string
      advantage:
        type: string
      flaw:
        type: string
      howWork:
        type: string
      logo:
        type: string
    title: MarketingInfoParameter
  ClientOfferCheckResponse:
    type: object
    required:
    - clientId
    - riskProfileClient
    properties:
      clientId:
        type: string
        description: id учётной записи Клиента
      riskProfileClient:
        type: string
        description: риск профиль клиента
      accounts:
        type: array
        description: Данные по генсогам и субсчетам клиента.
        items:
          $ref: '#/definitions/AccountDto'
    title: ClientOfferCheckResponse
  AccountDto:
    type: object
    required:
    - agreement
    - subaccounts
    properties:
      agreement:
        type: string
        description: Номер генсога
      subaccounts:
        type: array
        description: Список субсчетов
        items:
          type: string
    title: Account
  BuySPResponse:
    type: object
    required:
    - contractAmount
    - contractCurrency
    - clientId
    - contractId
    properties:
      clientId:
        type: string
        description: id учётной записи Клиента
      contractAmount:
        type: number
        description: Сумма контракта
      contractId:
        type: string
        description: id поручения присвоеный в MS SP
      contractCurrency:
        type: string
        description: Валюта контракта
    title: BuySPResponse
  ContainerDocumentResponse:
    type: object
    required:
    - status
    properties:
      content:
        $ref: '#/definitions/DocumentResponse'
      message:
        type: string
        description: Комментарий к отказу
      status:
        type: string
        description: 'Сатус ответа:SUCCESS - успешно, FAIL-отказ, WAIT - в процеесе'
        enum:
        - SUCCESS
        - FAIL
        - WAIT
    title: ContainerDocumentResponse
  DocumentResponse:
    type: object
    required:
    - commissionAmount
    - contractAmount
    - contractAmountWithCommission
    - contractCurrency
    - clientId
    - contractId
    - notificationDoc
    - orderDoc
    properties:
      clientId:
        type: string
        description: id учётной записи Клиента
      contractAmount:
        type: number
        description: Сумма контракта
      contractId:
        type: string
        description: id поручения присвоеный в MS SP
      contractCurrency:
        type: string
        description: Валюта контракта
      contractAmountRubles:
        type: number
        description: Сумма контракта в рублях, передается если сумма контракта не в рублях
      commissionAmount:
        type: number
        description: Сумма комиссии
      contractAmountWithCommission:
        type: number
        description: Сумма контракта с учётом комиссии
      orderDoc:
        type: string
        description: Печатная форма Поручения в формате base64
      notificationDoc:
        type: string
        description: Печатная форма Уведомления в формате base64
    title: DocumentResponse
  ErrorResponse:
    type: object
    required:
    - comment
    properties:
      comment:
        type: string
        description: описание проблемы которая привела к ошибке
    title: ErrorResponse